### ISSUE TITLE
BUG - seekbarfg_color in modernf.conf does not work

### ISSUE THREAD

**Issue by iripu** [FinnRaze/mpv-osc-modern-f#11]
In modernf.conf, if just the value of colour cahnged, the colour in the player becomes black. What I did:
`seekbarfg_color="0000FF" `

I had to add a space before = sign, but then it only removes the black colour, but it does not change the colour in the player:
`seekbarfg_color ="0000FF"`

Other parameters e.g. `timetotal=yes` works in modernf.conf.

**Comment by Samillion** [comment]
Indeed, `seekbarfg_color` does not work for me as well when set in `modernf.conf`.

**Comment by Samillion** [comment]
@iripu @FinnRaze 

Here is how to fix this, looking at mpv's `osc lua`:
https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua#L104-L106

They include a function to convert color so that you'd be able to use hex values:
```lua
local function osc_color_convert(color)
    return color:sub(6,7) .. color:sub(4,5) ..  color:sub(2,3)
end
```

So, simply adding that function to `modernf.lua` (before `local osc_styles`) and adjusting `SeekbarFg` to use the function, like this:
```lua
SeekbarFg = '{\\blur1\\bord1\\1c&H' .. osc_color_convert(user_opts.seekbarfg_color) .. '&}',
```

Will fix it and you'll be able to enter a hex color value in `modernf.conf`, for example:
```Properties
seekbarfg_color="2596be"
```

Screenshot:

![image](https://github.com/user-attachments/assets/6cbdc8c2-4722-41c6-a845-62aa27d2cef5)
